name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey there! it appears that this is your first issue here at SquareOne! We're sorry to hear that you're having issues, but just let us know what it is, and we'll get right back to you!"
        pr-message: "Wow, you just pulled me! No, I mean it! You just created your first pull-request!"
